unpackaged/main/default/objects/PersonalCircumstance__c/PersonalCircumstance__c.object-meta.xml
<CustomObject>
    <label>Personal Circumstance</label>
    <nameField>
        <displayFormat>PC# {00000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Circumstances</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PersonalCircumstance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Personal Circumstances</relationshipLabel>
    <relationshipName>PersonalCircumstances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PersonalCircumstance__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Indicates when the Personal Circumstance ends as it may occur in the past or future. Can also be left blank for ongoing circumstances.</description>
    <inlineHelpText>Use this field to store when the Personal Circumstance ends as it may be in the past or future. Leave it blank where the circumstance is ongoing.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/PersonalCircumstancesSelector.cls
public with sharing class PersonalCircumstancesSelector implements IBulkDeleteFactory {

    private IInsurancePoliciesSelector policySelector;

    public PersonalCircumstancesSelector(){

    }
    
    public List<PersonalCircumstance__c> getPersonalCircumstancesByAccountIds(Set<Id> accountIds){
        return [
            SELECT Id, Name, Account__c
            FROM PersonalCircumstance__c
            WHERE Account__c IN :accountIds
        ];
    }

    public List<SObject> getRecordsForBulkDelete(){
        List<SObject> objectsForDeletion = new List<SObject>();
        Map<Id,PersonalCircumstance__c> accountIdToPersonalCircumstances = new Map<Id,PersonalCircumstance__c>();

        List<PersonalCircumstance__c> candidateRecordsForDeletion = getPersonalCircumstancesWhereEndDateIsPastOrEndDateIsNull();

        for(PersonalCircumstance__c circumstance : candidateRecordsForDeletion){
            if(circumstance.EndDate__c != null){
                objectsForDeletion.add(circumstance);
            }else{
                accountIdToPersonalCircumstances.put(circumstance.Account__c,circumstance);
            }
        }

        for(Id accountId : removeAccountIdsWhereMostRecentPolicyEndDateIsWithinAYear(accountIdToPersonalCircumstances.keySet())){
            objectsForDeletion.add(accountIdToPersonalCircumstances.get(accountId));
        }

        return objectsForDeletion;

    }

    private List<PersonalCircumstance__c> getPersonalCircumstancesWhereEndDateIsPastOrEndDateIsNull(){
        return [
            SELECT Id, Account__c, EndDate__c
            FROM PersonalCircumstance__c
            WHERE EndDate__c < TODAY
            OR EndDate__c = null
        ];
    }

    private Set<Id> removeAccountIdsWhereMostRecentPolicyEndDateIsWithinAYear(Set<Id> accountIds){

        policySelector = (InsurancePoliciesSelector) new InsurancePoliciesSelector();

        AggregateResult[] policies = policySelector.getInsurancePoliciesGroupedByAccountId(accountIds);

        for(AggregateResult result : policies){
            if((DateTime) result.get('expr0') > System.today().addYears(-1)){
                accountIds.remove((Id) result.get('NameInsuredId'));
            }
        }

        return accountIds;

    }
    
    
}