unpackaged/main/default/objects/PersonalCircumstance__c/PersonalCircumstance__c.object-meta.xml
<CustomObject>
    <label>Personal Circumstance</label>
    <nameField>
        <displayFormat>PC# {00000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Circumstances</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PersonalCircumstance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Personal Circumstances</relationshipLabel>
    <relationshipName>PersonalCircumstances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PersonalCircumstance__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/PersonalCircumstance__c/fields/MethodOfContact__c.field-meta.xml
<CustomField>
    <fullName>MethodOfContact__c</fullName>
    <description>This field provides all methods that the customer can initially log their personal circumstance</description>
    <inlineHelpText>How did the customer first inform us of their personal circumstance</inlineHelpText>
    <label>Method of Contact</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>Webform</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/PersonalCircumstance__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Indicates when the Personal Circumstance begins as it may occur in the past or future</description>
    <inlineHelpText>Use this field to store when the Personal Circumstance begins/began as it may be in the past or future</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/PersonalCircumstance__c/fields/Support_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Support_Sub_Category__c</fullName>
    <description>This sub-category field will provide ability to log more granular details linked to Support Category field</description>
    <label>Support Sub-Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SupportCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bankrupt/IVA</fullName>
            </value>
            <value>
                <fullName>Debt/Low Income</fullName>
            </value>
            <value>
                <fullName>Emotional Distress</fullName>
            </value>
            <value>
                <fullName>Ability to Understand</fullName>
            </value>
            <value>
                <fullName>Language Barrier</fullName>
            </value>
            <value>
                <fullName>Computer Illiterate/Technology</fullName>
            </value>
            <value>
                <fullName>Lack of Insurance Knowledge/Experience</fullName>
            </value>
            <value>
                <fullName>Family Bereavement</fullName>
            </value>
            <value>
                <fullName>Family Illness</fullName>
            </value>
            <value>
                <fullName>Divorce/Separation</fullName>
            </value>
            <value>
                <fullName>Caring Responsibilities</fullName>
            </value>
            <value>
                <fullName>Major Incident</fullName>
            </value>
            <value>
                <fullName>Jobless/Redundancy</fullName>
            </value>
            <value>
                <fullName>Domestic Matters</fullName>
            </value>
            <value>
                <fullName>Physical Health</fullName>
            </value>
            <value>
                <fullName>Addiction</fullName>
            </value>
            <value>
                <fullName>Disability</fullName>
            </value>
            <value>
                <fullName>Mental Health</fullName>
            </value>
            <value>
                <fullName>Terminal Illness</fullName>
            </value>
            <value>
                <fullName>Surgery/Treatment/Hospital</fullName>
            </value>
            <value>
                <fullName>Blindness</fullName>
            </value>
            <value>
                <fullName>Deafness</fullName>
            </value>
            <value>
                <fullName>Mental Capacity</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/PersonalCircumstance__c/fields/SupportCategory__c.field-meta.xml
<CustomField>
    <fullName>SupportCategory__c</fullName>
    <description>This field indicates the type of personal circumstance as outlined by the FCA</description>
    <label>Support Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accessibility</fullName>
                <label>Capability</label>
            </value>
            <value>
                <fullName>Financial</fullName>
                <label>Resilience</label>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Life Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CircumstanceNotificationControllerTest.cls
@Istest
public class CircumstanceNotificationControllerTest {

    private static final String WITH_PERSONAL_CIRCUMSTANCE = 'TestingWithPersonalCircumstances';
    private static final String WITHOUT_PERSONAL_CIRCUMSTANCE = 'TestingWithoutPersonalCircumstances';

    @TestSetup
    static void makeData(){
        PC_TestDataFactory accountWithPersonalCircumstance = PC_TestDataFactory.createAccount(WITH_PERSONAL_CIRCUMSTANCE);
        PC_TestDataFactory accountWithOutPersonalCircumstance = PC_TestDataFactory.createAccount(WITHOUT_PERSONAL_CIRCUMSTANCE);

        insert new List<SObject>{
            (Account) accountWithPersonalCircumstance.getObj(),
            (Account) accountWithOutPersonalCircumstance.getObj()
        };

        InsurancePolicy policyWithPersonalCircumstance = createPolicy((Account) accountWithPersonalCircumstance.getObj());
        InsurancePolicy policyWithOutPersonalCircumstance = createPolicy((Account) accountWithOutPersonalCircumstance.getObj());

        insert new List<SObject>{
            createPersonalCircumstance((Account) accountWithPersonalCircumstance.getObj()),
            createOpportunity((Account) accountWithPersonalCircumstance.getObj()),
            createCase((Account) accountWithPersonalCircumstance.getObj()),
            policyWithPersonalCircumstance,
            policyWithOutPersonalCircumstance,
            createOpportunity((Account) accountWithOutPersonalCircumstance.getObj()),
            createCase((Account) accountWithOutPersonalCircumstance.getObj())
        };

        insert new List<Claim>{
            createClaim((Account) accountWithPersonalCircumstance.getObj(), policyWithPersonalCircumstance),
            createClaim((Account) accountWithOutPersonalCircumstance.getObj(), policyWithOutPersonalCircumstance)
        };
    }

    @IsTest
    static void additionalSupportNotificationHandler_ShouldDisplayNotificationAsTrue_WhenAccountHasPersonalCircumstances(){

        Account account = [SELECT Id FROM Account WHERE Name = :WITH_PERSONAL_CIRCUMSTANCE];

        Test.startTest();
        CircumstanceNotificationController.AdditionalSupportNotificationWrapper result = CircumstanceNotificationController.additionalSupportNotificationHandler(account.Id);
        Test.stopTest();

        Assert.areEqual(account.Id, result.ParentAccountId, 'Values should be the same');
        Assert.isTrue(result.DisplayNotification, 'DisplayNotification should be true');
        
    }

    @IsTest
    static void additionalSupportNotificationHandler_ShouldDisplayNotificationAsFalse_WhenAccountHasNoPersonalCircumstances(){

        Account account = [SELECT Id FROM Account WHERE Name = :WITHOUT_PERSONAL_CIRCUMSTANCE];

        Test.startTest();
        CircumstanceNotificationController.AdditionalSupportNotificationWrapper result = CircumstanceNotificationController.additionalSupportNotificationHandler(account.Id);
        Test.stopTest();

        Assert.areEqual(account.Id, result.ParentAccountId, 'Values should be the same');
        Assert.isFalse(result.DisplayNotification, 'DisplayNotification should be true');
        
    }

    @IsTest
    static void additionalSupportNotificationHandler_ShouldDisplayNotificationAsTrue_WhenParentAccountOnCaseHasPersonalCircumstances(){

        Account account = [SELECT Id FROM Account WHERE Name = :WITH_PERSONAL_CIRCUMSTANCE];
        Case cse = [SELECT Id FROM Case WHERE AccountId = :account.Id];
        
        Test.startTest();
        CircumstanceNotificationController.AdditionalSupportNotificationWrapper result = CircumstanceNotificationController.additionalSupportNotificationHandler(cse.Id);
        Test.stopTest();

        Assert.areEqual(account.Id, result.ParentAccountId, 'Values should be the same');
        Assert.isTrue(result.DisplayNotification, 'DisplayNotification should be true');
        
    }


    @IsTest
    static void additionalSupportNotificationHandler_ShouldDisplayNotificationAsFalse_WhenParentAccountOnCaseHasNoPersonalCircumstances(){

        Account account = [SELECT Id FROM Account WHERE Name = :WITHOUT_PERSONAL_CIRCUMSTANCE];
        Case cse = [SELECT Id FROM Case WHERE AccountId = :account.Id];

        Test.startTest();
        CircumstanceNotificationController.AdditionalSupportNotificationWrapper result = CircumstanceNotificationController.additionalSupportNotificationHandler(cse.Id);
        Test.stopTest();

        Assert.areEqual(account.Id, result.ParentAccountId, 'Values should be the same');
        Assert.isFalse(result.DisplayNotification, 'DisplayNotification should be true');
        
    }

    @IsTest
    static void additionalSupportNotificationHandler_ShouldDisplayNotificationAsTrue_WhenParentAccountOnOpportunityHasPersonalCircumstances(){

        Account account = [SELECT Id FROM Account WHERE Name = :WITH_PERSONAL_CIRCUMSTANCE];
        Opportunity opp = [SELECT Id FROM Opportunity WHERE AccountId = :account.Id];

        Test.startTest();
        CircumstanceNotificationController.AdditionalSupportNotificationWrapper result = CircumstanceNotificationController.additionalSupportNotificationHandler(opp.Id);
        Test.stopTest();

        Assert.areEqual(account.Id, result.ParentAccountId, 'Values should be the same');
        Assert.isTrue(result.DisplayNotification, 'DisplayNotification should be true');
        
    }


    @IsTest
    static void additionalSupportNotificationHandler_ShouldDisplayNotificationAsFalse_WhenParentAccountOnOpportunityHasNoPersonalCircumstances(){

        Account account = [SELECT Id FROM Account WHERE Name = :WITHOUT_PERSONAL_CIRCUMSTANCE];
        Opportunity opp = [SELECT Id FROM Opportunity WHERE AccountId = :account.Id];

        Test.startTest();
        CircumstanceNotificationController.AdditionalSupportNotificationWrapper result = CircumstanceNotificationController.additionalSupportNotificationHandler(account.Id);
        Test.stopTest();

        Assert.areEqual(account.Id, result.ParentAccountId, 'Values should be the same');
        Assert.isFalse(result.DisplayNotification, 'DisplayNotification should be true');
        
    }

    @IsTest
    static void additionalSupportNotificationHandler_ShouldDisplayNotificationAsTrue_WhenParentAccountOnPolicyHasPersonalCircumstances(){

        Account account = [SELECT Id FROM Account WHERE Name = :WITH_PERSONAL_CIRCUMSTANCE];
        InsurancePolicy policy = [SELECT Id FROM InsurancePolicy WHERE NameInsuredId = :account.Id];

        Test.startTest();
        CircumstanceNotificationController.AdditionalSupportNotificationWrapper result = CircumstanceNotificationController.additionalSupportNotificationHandler(policy.Id);
        Test.stopTest();

        Assert.areEqual(account.Id, result.ParentAccountId, 'Values should be the same');
        Assert.isTrue(result.DisplayNotification, 'DisplayNotification should be true');
        
    }

    @IsTest
    static void additionalSupportNotificationHandler_ShouldDisplayNotificationAsFalse_WhenParentAccountOnPolicyHasNoPersonalCircumstances(){

        Account account = [SELECT Id FROM Account WHERE Name = :WITHOUT_PERSONAL_CIRCUMSTANCE];
        InsurancePolicy policy = [SELECT Id FROM InsurancePolicy WHERE NameInsuredId = :account.Id];

        Test.startTest();
        CircumstanceNotificationController.AdditionalSupportNotificationWrapper result = CircumstanceNotificationController.additionalSupportNotificationHandler(policy.Id);
        Test.stopTest();

        Assert.areEqual(account.Id, result.ParentAccountId, 'Values should be the same');
        Assert.isFalse(result.DisplayNotification, 'DisplayNotification should be true');
        
    }

    @IsTest
    static void additionalSupportNotificationHandler_ShouldDisplayNotificationAsTrue_WhenParentAccountOnClaimHasPersonalCircumstances(){

        Account account = [SELECT Id FROM Account WHERE Name = :WITH_PERSONAL_CIRCUMSTANCE];
        Claim claim = [SELECT Id FROM Claim WHERE AccountId = :account.Id];

        Test.startTest();
        CircumstanceNotificationController.AdditionalSupportNotificationWrapper result = CircumstanceNotificationController.additionalSupportNotificationHandler(claim.Id);
        Test.stopTest();

        Assert.areEqual(account.Id, result.ParentAccountId, 'Values should be the same');
        Assert.isTrue(result.DisplayNotification, 'DisplayNotification should be true');
        
    }

    @IsTest
    static void additionalSupportNotificationHandler_ShouldDisplayNotificationAsFalse_WhenParentAccountOnClaimHasNoPersonalCircumstances(){

        Account account = [SELECT Id FROM Account WHERE Name = :WITHOUT_PERSONAL_CIRCUMSTANCE];
        Claim claim = [SELECT Id FROM Claim WHERE AccountId = :account.Id];

        Test.startTest();
        CircumstanceNotificationController.AdditionalSupportNotificationWrapper result = CircumstanceNotificationController.additionalSupportNotificationHandler(claim.Id);
        Test.stopTest();

        Assert.areEqual(account.Id, result.ParentAccountId, 'Values should be the same');
        Assert.isFalse(result.DisplayNotification, 'DisplayNotification should be true');
        
    }

    private static PersonalCircumstance__c createPersonalCircumstance(Account parentAccount){
        return new PersonalCircumstance__c(
            Account__c = parentAccount.Id,
            Details__c = 'Test Details',
            MethodOfContact__c = 'Phone',
            StartDate__c = System.today(),
            SupportCategory__c = 'Health',
            Support_Sub_Category__c = 'Addiction'
        );
    }

    private static Opportunity createOpportunity(Account parentAccount){
        return new Opportunity(
            AccountId = parentAccount.Id,
            Name = 'Test Opportunity',
            CloseDate = System.today(),
            StageName = 'Full Quote'
        );
    }

    private static Case createCase(Account parentAccount){
        return new Case(
            AccountId = parentAccount.Id,
            Status = 'New',
            Origin = 'Email',
            Priority = 'Low'
        );
    }

    private static InsurancePolicy createPolicy(Account parentAccount){
        return new InsurancePolicy(
            Name = 'Test Policy',
            NameInsuredId = parentAccount.Id
        );
    }

    public static Claim createClaim(Account parentAccount, InsurancePolicy policy){
        return new Claim(
            Name = 'Test Claim',
            AccountId = parentAccount.Id,
            PolicyNumberId = policy.Id
        );
    }

}