unpackaged/main/default/objects/InsurancePolicy/fields/DurationEnd__c.field-meta.xml
<CustomField>
    <fullName>DurationEnd__c</fullName>
    <label>Duration End</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/InsurancePoliciesSelector.cls
public with sharing class InsurancePoliciesSelector implements IInsurancePoliciesSelector{

    public Map<String,InsurancePolicy> getInsurancePolicyMapByUUID(Set<String> sourceUUIDs){

        Map<String,InsurancePolicy> mapToReturn = new Map<String,InsurancePolicy>();
        
        List<InsurancePolicy> insurancePolicies = [
            SELECT Id,SourceRecord_UUID__c	
            FROM InsurancePolicy
            WHERE SourceRecord_UUID__c
            IN :sourceUUIDs
        ];
        
        for(InsurancePolicy policy : insurancePolicies){
            mapToReturn.put(policy.SourceRecord_UUID__c, policy);
        }
        
        return mapToReturn;
        
    }

    public AggregateResult[] getInsurancePoliciesGroupedByAccountId(Set<Id> parentAccountIds){
        return [
            SELECT NameInsuredId, MAX(DurationEnd__c)
            FROM InsurancePolicy
            WHERE NameInsuredId IN :parentAccountIds
            GROUP BY NameInsuredId
        ];
    }

}