unpackaged/main/default/objects/InsurancePolicy/fields/DurationEnd__c.field-meta.xml
<CustomField>
    <fullName>DurationEnd__c</fullName>
    <label>Duration End</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/PersonalCircumstance__c/PersonalCircumstance__c.object-meta.xml
<CustomObject>
    <label>Personal Circumstance</label>
    <nameField>
        <displayFormat>PC# {00000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Circumstances</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PersonalCircumstance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Personal Circumstances</relationshipLabel>
    <relationshipName>PersonalCircumstances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PersonalCircumstance__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/PersonalCircumstance__c/fields/MethodOfContact__c.field-meta.xml
<CustomField>
    <fullName>MethodOfContact__c</fullName>
    <description>This field provides all methods that the customer can initially log their personal circumstance</description>
    <inlineHelpText>How did the customer first inform us of their personal circumstance</inlineHelpText>
    <label>Method of Contact</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>Webform</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/PersonalCircumstance__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Indicates when the Personal Circumstance begins as it may occur in the past or future</description>
    <inlineHelpText>Use this field to store when the Personal Circumstance begins/began as it may be in the past or future</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/PersonalCircumstance__c/fields/Support_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Support_Sub_Category__c</fullName>
    <description>This sub-category field will provide ability to log more granular details linked to Support Category field</description>
    <label>Support Sub-Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SupportCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bankrupt/IVA</fullName>
            </value>
            <value>
                <fullName>Debt/Low Income</fullName>
            </value>
            <value>
                <fullName>Emotional Distress</fullName>
            </value>
            <value>
                <fullName>Ability to Understand</fullName>
            </value>
            <value>
                <fullName>Language Barrier</fullName>
            </value>
            <value>
                <fullName>Computer Illiterate/Technology</fullName>
            </value>
            <value>
                <fullName>Lack of Insurance Knowledge/Experience</fullName>
            </value>
            <value>
                <fullName>Family Bereavement</fullName>
            </value>
            <value>
                <fullName>Family Illness</fullName>
            </value>
            <value>
                <fullName>Divorce/Separation</fullName>
            </value>
            <value>
                <fullName>Caring Responsibilities</fullName>
            </value>
            <value>
                <fullName>Major Incident</fullName>
            </value>
            <value>
                <fullName>Jobless/Redundancy</fullName>
            </value>
            <value>
                <fullName>Domestic Matters</fullName>
            </value>
            <value>
                <fullName>Physical Health</fullName>
            </value>
            <value>
                <fullName>Addiction</fullName>
            </value>
            <value>
                <fullName>Disability</fullName>
            </value>
            <value>
                <fullName>Mental Health</fullName>
            </value>
            <value>
                <fullName>Terminal Illness</fullName>
            </value>
            <value>
                <fullName>Surgery/Treatment/Hospital</fullName>
            </value>
            <value>
                <fullName>Blindness</fullName>
            </value>
            <value>
                <fullName>Deafness</fullName>
            </value>
            <value>
                <fullName>Mental Capacity</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/PersonalCircumstance__c/fields/SupportCategory__c.field-meta.xml
<CustomField>
    <fullName>SupportCategory__c</fullName>
    <description>This field indicates the type of personal circumstance as outlined by the FCA</description>
    <label>Support Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accessibility</fullName>
                <label>Capability</label>
            </value>
            <value>
                <fullName>Financial</fullName>
                <label>Resilience</label>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Life Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/PersonalCircumstancesSelectorTest.cls
@isTest
public with sharing class PersonalCircumstancesSelectorTest {

    @TestSetup
    static void makeData(){

        PC_TestDataFactory accountWithPersonalCircumstance = PC_TestDataFactory.createAccount('Test');

        accountWithPersonalCircumstance.insertObj();

        insert new PersonalCircumstance__c(
            Account__c = accountWithPersonalCircumstance.getObj().Id,
            Details__c = 'Test Details',
            MethodOfContact__c = 'Phone',
            StartDate__c = System.today(),
            SupportCategory__c = 'Health',
            Support_Sub_Category__c = 'Addiction'
        );

    }

    @IsTest
    static void getPersonalCircumstancesByAccountIds_ShouldReturnPersonalCircumstances_WhenCalled(){

        PersonalCircumstancesSelector selector = new PersonalCircumstancesSelector();
        Account account = [SELECT Id FROM Account LIMIT 1];
        
        Test.startTest();
        List<PersonalCircumstance__c> result = selector.getPersonalCircumstancesByAccountIds(new Set<Id>{ account.Id });
        Test.stopTest();

        Assert.areEqual( 1, result.size(), 'Selector should have returned a Personal Circumstance');
        
    }

    @IsTest
    static void getRecordsForBulkDelete_ShouldReturnLapsedPersonalCircumstance_WhenPolicyEndDateIsNull(){

        PersonalCircumstancesSelector systemUnderTest = new PersonalCircumstancesSelector();
        Integer expectedResult = 1;

        Account account = [SELECT Id FROM Account LIMIT 1];

        insert new InsurancePolicy(
            Name = 'Test Policy1',
            NameInsuredId = account.Id
        );

        Test.startTest();
        List<SObject> result = systemUnderTest.getRecordsForBulkDelete();
        Test.stopTest();

        system.assertEquals(1, result.size(), 'Records to delete should have returned one record');
        
    }

    @IsTest
    static void getRecordsForBulkDelete_ShouldReturnLapsedPersonalCircumstance_WhenPolicyEndDateOverAYearOld(){

        PersonalCircumstancesSelector systemUnderTest = new PersonalCircumstancesSelector();
        Integer expectedResult = 1;

        Account account = [SELECT Id FROM Account LIMIT 1];

        insert new InsurancePolicy(
            Name = 'Test Policy1',
            NameInsuredId = account.Id,
            DurationEnd__c = System.today().addYears(-1)
        );

        Test.startTest();
        List<SObject> result = systemUnderTest.getRecordsForBulkDelete();
        Test.stopTest();

        system.assertEquals(expectedResult, result.size(), 'Records to delete should have returned one record');
        
    }

    @IsTest
    static void getRecordsForBulkDelete_ShouldNotReturnLapsedPersonalCircumstance_WhenPolicyEndDatePast(){

        PersonalCircumstancesSelector systemUnderTest = new PersonalCircumstancesSelector();
        Integer expectedResult = 0;

        Account account = [SELECT Id FROM Account LIMIT 1];

        insert new InsurancePolicy(
            Name = 'Test Policy1',
            NameInsuredId = account.Id,
            DurationEnd__c = System.today().addDays(-1)
        );

        Test.startTest();
        List<SObject> result = systemUnderTest.getRecordsForBulkDelete();
        Test.stopTest();

        system.assertEquals(expectedResult, result.size(), 'Records to delete should not have returned any records');
        
    }

    @IsTest
    static void getRecordsForBulkDelete_ShouldNotReturnLapsedPersonalCircumstance_WhenPolicyEndDateIsTodayOrInFuture(){

        PersonalCircumstancesSelector systemUnderTest = new PersonalCircumstancesSelector();
        Integer expectedResult = 0;

        Account account = [SELECT Id FROM Account LIMIT 1];

        insert new List<InsurancePolicy>{
            new InsurancePolicy(
                Name = 'Test Policy1',
                NameInsuredId = account.Id,
                DurationEnd__c = System.today()
            ), new InsurancePolicy(
                Name = 'Test Policy2',
                NameInsuredId = account.Id,
                DurationEnd__c = System.today().addDays(13)
            )
        };

        Test.startTest();
        List<SObject> result = systemUnderTest.getRecordsForBulkDelete();
        Test.stopTest();

        system.assertEquals(expectedResult, result.size(), 'Records to delete should not have returned any records');
        
    }

}